// https://en.wikipedia.org/wiki/ISO_4217
export enum CurrencyCode {
  AED = 'AED',
  AFN = 'AFN',
  ALL = 'ALL',
  AMD = 'AMD',
  ANG = 'ANG',
  AOA = 'AOA',
  ARS = 'ARS',
  AUD = 'AUD',
  AWG = 'AWG',
  AZN = 'AZN',
  BAM = 'BAM',
  BBD = 'BBD',
  BDT = 'BDT',
  BGN = 'BGN',
  BHD = 'BHD',
  BIF = 'BIF',
  BMD = 'BMD',
  BND = 'BND',
  BOB = 'BOB',
  BRL = 'BRL',
  BSD = 'BSD',
  BTN = 'BTN',
  BWP = 'BWP',
  BYN = 'BYN',
  BZD = 'BZD',
  CAD = 'CAD',
  CDF = 'CDF',
  CHF = 'CHF',
  CLP = 'CLP',
  CNY = 'CNY',
  COP = 'COP',
  CRC = 'CRC',
  CUC = 'CUC',
  CUP = 'CUP',
  CVE = 'CVE',
  CZK = 'CZK',
  DJF = 'DJF',
  DKK = 'DKK',
  DOP = 'DOP',
  DZD = 'DZD',
  EGP = 'EGP',
  ERN = 'ERN',
  ETB = 'ETB',
  EUR = 'EUR',
  FJD = 'FJD',
  FKP = 'FKP',
  GBP = 'GBP',
  GEL = 'GEL',
  GGP = 'GGP',
  GHS = 'GHS',
  GIP = 'GIP',
  GMD = 'GMD',
  GNF = 'GNF',
  GTQ = 'GTQ',
  GYD = 'GYD',
  HKD = 'HKD',
  HNL = 'HNL',
  HRK = 'HRK',
  HTG = 'HTG',
  HUF = 'HUF',
  IDR = 'IDR',
  ILS = 'ILS',
  IMP = 'IMP',
  INR = 'INR',
  IQD = 'IQD',
  IRR = 'IRR',
  ISK = 'ISK',
  JEP = 'JEP',
  JMD = 'JMD',
  JOD = 'JOD',
  JPY = 'JPY',
  KES = 'KES',
  KGS = 'KGS',
  KHR = 'KHR',
  KMF = 'KMF',
  KPW = 'KPW',
  KRW = 'KRW',
  KWD = 'KWD',
  KYD = 'KYD',
  KZT = 'KZT',
  LAK = 'LAK',
  LBP = 'LBP',
  LKR = 'LKR',
  LRD = 'LRD',
  LSL = 'LSL',
  LYD = 'LYD',
  MAD = 'MAD',
  MDL = 'MDL',
  MGA = 'MGA',
  MKD = 'MKD',
  MMK = 'MMK',
  MNT = 'MNT',
  MOP = 'MOP',
  MRU = 'MRU',
  MUR = 'MUR',
  MVR = 'MVR',
  MWK = 'MWK',
  MXN = 'MXN',
  MYR = 'MYR',
  MZN = 'MZN',
  NAD = 'NAD',
  NGN = 'NGN',
  NIO = 'NIO',
  NOK = 'NOK',
  NPR = 'NPR',
  NZD = 'NZD',
  OMR = 'OMR',
  PAB = 'PAB',
  PEN = 'PEN',
  PGK = 'PGK',
  PHP = 'PHP',
  PKR = 'PKR',
  PLN = 'PLN',
  PYG = 'PYG',
  QAR = 'QAR',
  RON = 'RON',
  RSD = 'RSD',
  RUB = 'RUB',
  RWF = 'RWF',
  SAR = 'SAR',
  SBD = 'SBD',
  SCR = 'SCR',
  SDG = 'SDG',
  SEK = 'SEK',
  SGD = 'SGD',
  SHP = 'SHP',
  SLL = 'SLL',
  SOS = 'SOS',
  SRD = 'SRD',
  SSP = 'SSP',
  STN = 'STN',
  SYP = 'SYP',
  SZL = 'SZL',
  THB = 'THB',
  TJS = 'TJS',
  TMT = 'TMT',
  TND = 'TND',
  TOP = 'TOP',
  TRY = 'TRY',
  TTD = 'TTD',
  TWD = 'TWD',
  TZS = 'TZS',
  UAH = 'UAH',
  UGX = 'UGX',
  USD = 'USD',
  UYU = 'UYU',
  UZS = 'UZS',
  VES = 'VES',
  VND = 'VND',
  VUV = 'VUV',
  WST = 'WST',
  XAF = 'XAF',
  XCD = 'XCD',
  XOF = 'XOF',
  XPF = 'XPF',
  YER = 'YER',
  ZAR = 'ZAR',
  ZMW = 'ZMW',
  ZWL = 'ZWL',
}

export const currencies = [
  { code: CurrencyCode.AED, name: "United Arab Emirates dirham" },
  { code: CurrencyCode.AFN, name: "Afghan afghani" },
  { code: CurrencyCode.ALL, name: "Albanian lek" },
  { code: CurrencyCode.AMD, name: "Armenian dram" },
  { code: CurrencyCode.ANG, name: "Netherlands Antillean guilder" },
  { code: CurrencyCode.AOA, name: "Angolan kwanza" },
  { code: CurrencyCode.ARS, name: "Argentine peso" },
  { code: CurrencyCode.AUD, name: "Australian dollar" },
  { code: CurrencyCode.AWG, name: "Aruban florin" },
  { code: CurrencyCode.AZN, name: "Azerbaijani manat" },
  { code: CurrencyCode.BAM, name: "Bosnia and Herzegovina convertible mark" },
  { code: CurrencyCode.BBD, name: "Barbadian dollar" },
  { code: CurrencyCode.BDT, name: "Bangladeshi taka" },
  { code: CurrencyCode.BGN, name: "Bulgarian lev" },
  { code: CurrencyCode.BHD, name: "Bahraini dinar" },
  { code: CurrencyCode.BIF, name: "Burundian franc" },
  { code: CurrencyCode.BMD, name: "Bermudian dollar" },
  { code: CurrencyCode.BND, name: "Brunei dollar" },
  { code: CurrencyCode.BOB, name: "Bolivian boliviano" },
  { code: CurrencyCode.BRL, name: "Brazilian real" },
  { code: CurrencyCode.BSD, name: "Bahamian dollar" },
  { code: CurrencyCode.BTN, name: "Bhutanese ngultrum" },
  { code: CurrencyCode.BWP, name: "Botswana pula" },
  { code: CurrencyCode.BYN, name: "Belarusian ruble" },
  { code: CurrencyCode.BZD, name: "Belize dollar" },
  { code: CurrencyCode.CAD, name: "Canadian dollar" },
  { code: CurrencyCode.CDF, name: "Congolese franc" },
  { code: CurrencyCode.CHF, name: "Swiss franc" },
  { code: CurrencyCode.CLP, name: "Chilean peso" },
  { code: CurrencyCode.CNY, name: "Chinese yuan" },
  { code: CurrencyCode.COP, name: "Colombian peso" },
  { code: CurrencyCode.CRC, name: "Costa Rican colón" },
  { code: CurrencyCode.CUC, name: "Cuban convertible peso" },
  { code: CurrencyCode.CUP, name: "Cuban peso" },
  { code: CurrencyCode.CVE, name: "Cape Verdean escudo" },
  { code: CurrencyCode.CZK, name: "Czech koruna" },
  { code: CurrencyCode.DJF, name: "Djiboutian franc" },
  { code: CurrencyCode.DKK, name: "Danish krone" },
  { code: CurrencyCode.DOP, name: "Dominican peso" },
  { code: CurrencyCode.DZD, name: "Algerian dinar" },
  { code: CurrencyCode.EGP, name: "Egyptian pound" },
  { code: CurrencyCode.ERN, name: "Eritrean nakfa" },
  { code: CurrencyCode.ETB, name: "Ethiopian birr" },
  { code: CurrencyCode.EUR, name: "Euro" },
  { code: CurrencyCode.FJD, name: "Fijian dollar" },
  { code: CurrencyCode.FKP, name: "Falkland Islands pound" },
  { code: CurrencyCode.GBP, name: "British pound" },
  { code: CurrencyCode.GEL, name: "Georgian lari" },
  { code: CurrencyCode.GGP, name: "Guernsey pound" },
  { code: CurrencyCode.GHS, name: "Ghanaian cedi" },
  { code: CurrencyCode.GIP, name: "Gibraltar pound" },
  { code: CurrencyCode.GMD, name: "Gambian dalasi" },
  { code: CurrencyCode.GNF, name: "Guinean franc" },
  { code: CurrencyCode.GTQ, name: "Guatemalan quetzal" },
  { code: CurrencyCode.GYD, name: "Guyanese dollar" },
  { code: CurrencyCode.HKD, name: "Hong Kong dollar" },
  { code: CurrencyCode.HNL, name: "Honduran lempira" },
  { code: CurrencyCode.HRK, name: "Croatian kuna" },
  { code: CurrencyCode.HTG, name: "Haitian gourde" },
  { code: CurrencyCode.HUF, name: "Hungarian forint" },
  { code: CurrencyCode.IDR, name: "Indonesian rupiah" },
  { code: CurrencyCode.ILS, name: "Israeli new shekel" },
  { code: CurrencyCode.IMP, name: "Manx pound" },
  { code: CurrencyCode.INR, name: "Indian rupee" },
  { code: CurrencyCode.IQD, name: "Iraqi dinar" },
  { code: CurrencyCode.IRR, name: "Iranian rial" },
  { code: CurrencyCode.ISK, name: "Icelandic króna" },
  { code: CurrencyCode.JEP, name: "Jersey pound" },
  { code: CurrencyCode.JMD, name: "Jamaican dollar" },
  { code: CurrencyCode.JOD, name: "Jordanian dinar" },
  { code: CurrencyCode.JPY, name: "Japanese yen" },
  { code: CurrencyCode.KES, name: "Kenyan shilling" },
  { code: CurrencyCode.KGS, name: "Kyrgyzstani som" },
  { code: CurrencyCode.KHR, name: "Cambodian riel" },
  { code: CurrencyCode.KMF, name: "Comorian franc" },
  { code: CurrencyCode.KPW, name: "North Korean won" },
  { code: CurrencyCode.KRW, name: "South Korean won" },
  { code: CurrencyCode.KWD, name: "Kuwaiti dinar" },
  { code: CurrencyCode.KYD, name: "Cayman Islands dollar" },
  { code: CurrencyCode.KZT, name: "Kazakhstani tenge" },
  { code: CurrencyCode.LAK, name: "Lao kip" },
  { code: CurrencyCode.LBP, name: "Lebanese pound" },
  { code: CurrencyCode.LKR, name: "Sri Lankan rupee" },
  { code: CurrencyCode.LRD, name: "Liberian dollar" },
  { code: CurrencyCode.LSL, name: "Lesotho loti" },
  { code: CurrencyCode.LYD, name: "Libyan dinar" },
  { code: CurrencyCode.MAD, name: "Moroccan dirham" },
  { code: CurrencyCode.MDL, name: "Moldovan leu" },
  { code: CurrencyCode.MGA, name: "Malagasy ariary" },
  { code: CurrencyCode.MKD, name: "Macedonian denar" },
  { code: CurrencyCode.MMK, name: "Myanmar kyat" },
  { code: CurrencyCode.MNT, name: "Mongolian tögrög" },
  { code: CurrencyCode.MOP, name: "Macanese pataca" },
  { code: CurrencyCode.MRU, name: "Mauritanian ouguiya" },
  { code: CurrencyCode.MUR, name: "Mauritian rupee" },
  { code: CurrencyCode.MVR, name: "Maldivian rufiyaa" },
  { code: CurrencyCode.MWK, name: "Malawian kwacha" },
  { code: CurrencyCode.MXN, name: "Mexican peso" },
  { code: CurrencyCode.MYR, name: "Malaysian ringgit" },
  { code: CurrencyCode.MZN, name: "Mozambican metical" },
  { code: CurrencyCode.NAD, name: "Namibian dollar" },
  { code: CurrencyCode.NGN, name: "Nigerian naira" },
  { code: CurrencyCode.NIO, name: "Nicaraguan córdoba" },
  { code: CurrencyCode.NOK, name: "Norwegian krone" },
  { code: CurrencyCode.NPR, name: "Nepalese rupee" },
  { code: CurrencyCode.NZD, name: "New Zealand dollar" },
  { code: CurrencyCode.OMR, name: "Omani rial" },
  { code: CurrencyCode.PAB, name: "Panamanian balboa" },
  { code: CurrencyCode.PEN, name: "Peruvian sol" },
  { code: CurrencyCode.PGK, name: "Papua New Guinean kina" },
  { code: CurrencyCode.PHP, name: "Philippine peso" },
  { code: CurrencyCode.PKR, name: "Pakistani rupee" },
  { code: CurrencyCode.PLN, name: "Polish złoty" },
  { code: CurrencyCode.PYG, name: "Paraguayan guaraní" },
  { code: CurrencyCode.QAR, name: "Qatari riyal" },
  { code: CurrencyCode.RON, name: "Romanian leu" },
  { code: CurrencyCode.RSD, name: "Serbian dinar" },
  { code: CurrencyCode.RUB, name: "Russian ruble" },
  { code: CurrencyCode.RWF, name: "Rwandan franc" },
  { code: CurrencyCode.SAR, name: "Saudi riyal" },
  { code: CurrencyCode.SBD, name: "Solomon Islands dollar" },
  { code: CurrencyCode.SCR, name: "Seychellois rupee" },
  { code: CurrencyCode.SDG, name: "Sudanese pound" },
  { code: CurrencyCode.SEK, name: "Swedish krona" },
  { code: CurrencyCode.SGD, name: "Singapore dollar" },
  { code: CurrencyCode.SHP, name: "Saint Helena pound" },
  { code: CurrencyCode.SLL, name: "Sierra Leonean leone" },
  { code: CurrencyCode.SOS, name: "Somali shilling" },
  { code: CurrencyCode.SRD, name: "Surinamese dollar" },
  { code: CurrencyCode.SSP, name: "South Sudanese pound" },
  { code: CurrencyCode.STN, name: "São Tomé and Príncipe dobra" },
  { code: CurrencyCode.SYP, name: "Syrian pound" },
  { code: CurrencyCode.SZL, name: "Swazi lilangeni" },
  { code: CurrencyCode.THB, name: "Thai baht" },
  { code: CurrencyCode.TJS, name: "Tajikistani somoni" },
  { code: CurrencyCode.TMT, name: "Turkmenistan manat" },
  { code: CurrencyCode.TND, name: "Tunisian dinar" },
  { code: CurrencyCode.TOP, name: "Tongan paʻanga" },
  { code: CurrencyCode.TRY, name: "Turkish lira" },
  { code: CurrencyCode.TTD, name: "Trinidad and Tobago dollar" },
  { code: CurrencyCode.TWD, name: "New Taiwan dollar" },
  { code: CurrencyCode.TZS, name: "Tanzanian shilling" },
  { code: CurrencyCode.UAH, name: "Ukrainian hryvnia" },
  { code: CurrencyCode.UGX, name: "Ugandan shilling" },
  { code: CurrencyCode.USD, name: "United States dollar" },
  { code: CurrencyCode.UYU, name: "Uruguayan peso" },
  { code: CurrencyCode.UZS, name: "Uzbekistani som" },
  { code: CurrencyCode.VES, name: "Venezuelan bolívar soberano" },
  { code: CurrencyCode.VND, name: "Vietnamese đồng" },
  { code: CurrencyCode.VUV, name: "Vanuatu vatu" },
  { code: CurrencyCode.WST, name: "Samoan tala" },
  { code: CurrencyCode.XAF, name: "CFA franc BEAC" },
  { code: CurrencyCode.XCD, name: "East Caribbean dollar" },
  { code: CurrencyCode.XOF, name: "CFA franc BCEAO" },
  { code: CurrencyCode.XPF, name: "CFP franc" },
  { code: CurrencyCode.YER, name: "Yemeni rial" },
  { code: CurrencyCode.ZAR, name: "South African rand" },
  { code: CurrencyCode.ZMW, name: "Zambian kwacha" },
  { code: CurrencyCode.ZWL, name: "Zimbabwean dollar" },
];
