// https://datahub.io/core/language-codes
export enum LanguageCode {
  AA = "aa",
  AA_DJ = "aa-DJ",
  AA_ER = "aa-ER",
  AA_ET = "aa-ET",
  AB = "ab",
  AB_GE = "ab-GE",
  AF = "af",
  AF_NA = "af-NA",
  AF_ZA = "af-ZA",
  AGQ = "agq",
  AGQ_CM = "agq-CM",
  AK = "ak",
  AK_GH = "ak-GH",
  AM = "am",
  AM_ET = "am-ET",
  AN = "an",
  AN_ES = "an-ES",
  ANN = "ann",
  ANN_NG = "ann-NG",
  APC = "apc",
  APC_SY = "apc-SY",
  AR = "ar",
  AR_001 = "ar-001",
  AR_AE = "ar-AE",
  AR_BH = "ar-BH",
  AR_DJ = "ar-DJ",
  AR_DZ = "ar-DZ",
  AR_EG = "ar-EG",
  AR_EH = "ar-EH",
  AR_ER = "ar-ER",
  AR_IL = "ar-IL",
  AR_IQ = "ar-IQ",
  AR_JO = "ar-JO",
  AR_KM = "ar-KM",
  AR_KW = "ar-KW",
  AR_LB = "ar-LB",
  AR_LY = "ar-LY",
  AR_MA = "ar-MA",
  AR_MR = "ar-MR",
  AR_OM = "ar-OM",
  AR_PS = "ar-PS",
  AR_QA = "ar-QA",
  AR_SA = "ar-SA",
  AR_SD = "ar-SD",
  AR_SO = "ar-SO",
  AR_SS = "ar-SS",
  AR_SY = "ar-SY",
  AR_TD = "ar-TD",
  AR_TN = "ar-TN",
  AR_YE = "ar-YE",
  ARN = "arn",
  ARN_CL = "arn-CL",
  AS = "as",
  AS_IN = "as-IN",
  ASA = "asa",
  ASA_TZ = "asa-TZ",
  AST = "ast",
  AST_ES = "ast-ES",
  AZ = "az",
  AZ_ARAB = "az-Arab",
  AZ_ARAB_IQ = "az-Arab-IQ",
  AZ_ARAB_IR = "az-Arab-IR",
  AZ_ARAB_TR = "az-Arab-TR",
  AZ_CYRL = "az-Cyrl",
  AZ_CYRL_AZ = "az-Cyrl-AZ",
  AZ_LATN = "az-Latn",
  AZ_LATN_AZ = "az-Latn-AZ",
  BA = "ba",
  BA_RU = "ba-RU",
  BAL = "bal",
  BAL_ARAB = "bal-Arab",
  BAL_ARAB_PK = "bal-Arab-PK",
  BAL_LATN = "bal-Latn",
  BAL_LATN_PK = "bal-Latn-PK",
  BAS = "bas",
  BAS_CM = "bas-CM",
  BE = "be",
  BE_BY = "be-BY",
  BE_TARASK = "be-TARASK",
  BEM = "bem",
  BEM_ZM = "bem-ZM",
  BEW = "bew",
  BEW_ID = "bew-ID",
  BEZ = "bez",
  BEZ_TZ = "bez-TZ",
  BG = "bg",
  BG_BG = "bg-BG",
  BGC = "bgc",
  BGC_IN = "bgc-IN",
  BGN = "bgn",
  BGN_AE = "bgn-AE",
  BGN_AF = "bgn-AF",
  BGN_IR = "bgn-IR",
  BGN_OM = "bgn-OM",
  BGN_PK = "bgn-PK",
  BHO = "bho",
  BHO_IN = "bho-IN",
  BLO = "blo",
  BLO_BJ = "blo-BJ",
  BLT = "blt",
  BLT_VN = "blt-VN",
  BM = "bm",
  BM_ML = "bm-ML",
  BM_NKOO = "bm-Nkoo",
  BM_NKOO_ML = "bm-Nkoo-ML",
  BN = "bn",
  BN_BD = "bn-BD",
  BN_IN = "bn-IN",
  BO = "bo",
  BO_CN = "bo-CN",
  BO_IN = "bo-IN",
  BR = "br",
  BR_FR = "br-FR",
  BRX = "brx",
  BRX_IN = "brx-IN",
  BS = "bs",
  BS_CYRL = "bs-Cyrl",
  BS_CYRL_BA = "bs-Cyrl-BA",
  BS_LATN = "bs-Latn",
  BS_LATN_BA = "bs-Latn-BA",
  BSS = "bss",
  BSS_CM = "bss-CM",
  BYN = "byn",
  BYN_ER = "byn-ER",
  CA = "ca",
  CA_AD = "ca-AD",
  CA_ES = "ca-ES",
  CA_ES_VALENCIA = "ca-ES-VALENCIA",
  CA_FR = "ca-FR",
  CA_IT = "ca-IT",
  CAD = "cad",
  CAD_US = "cad-US",
  CCH = "cch",
  CCH_NG = "cch-NG",
  CCP = "ccp",
  CCP_BD = "ccp-BD",
  CCP_IN = "ccp-IN",
  CE = "ce",
  CE_RU = "ce-RU",
  CEB = "ceb",
  CEB_PH = "ceb-PH",
  CGG = "cgg",
  CGG_UG = "cgg-UG",
  CHO = "cho",
  CHO_US = "cho-US",
  CHR = "chr",
  CHR_US = "chr-US",
  CIC = "cic",
  CIC_US = "cic-US",
  CKB = "ckb",
  CKB_IQ = "ckb-IQ",
  CKB_IR = "ckb-IR",
  CO = "co",
  CO_FR = "co-FR",
  CS = "cs",
  CS_CZ = "cs-CZ",
  CSW = "csw",
  CSW_CA = "csw-CA",
  CU = "cu",
  CU_RU = "cu-RU",
  CV = "cv",
  CV_RU = "cv-RU",
  CY = "cy",
  CY_GB = "cy-GB",
  DA = "da",
  DA_DK = "da-DK",
  DA_GL = "da-GL",
  DAV = "dav",
  DAV_KE = "dav-KE",
  DE = "de",
  DE_AT = "de-AT",
  DE_BE = "de-BE",
  DE_CH = "de-CH",
  DE_DE = "de-DE",
  DE_IT = "de-IT",
  DE_LI = "de-LI",
  DE_LU = "de-LU",
  DJE = "dje",
  DJE_NE = "dje-NE",
  DOI = "doi",
  DOI_IN = "doi-IN",
  DSB = "dsb",
  DSB_DE = "dsb-DE",
  DUA = "dua",
  DUA_CM = "dua-CM",
  DV = "dv",
  DV_MV = "dv-MV",
  DYO = "dyo",
  DYO_SN = "dyo-SN",
  DZ = "dz",
  DZ_BT = "dz-BT",
  EBU = "ebu",
  EBU_KE = "ebu-KE",
  EE = "ee",
  EE_GH = "ee-GH",
  EE_TG = "ee-TG",
  EL = "el",
  EL_CY = "el-CY",
  EL_GR = "el-GR",
  EL_POLYTON = "el-POLYTON",
  EN = "en",
  EN_001 = "en-001",
  EN_150 = "en-150",
  EN_AE = "en-AE",
  EN_AG = "en-AG",
  EN_AI = "en-AI",
  EN_AS = "en-AS",
  EN_AT = "en-AT",
  EN_AU = "en-AU",
  EN_BB = "en-BB",
  EN_BE = "en-BE",
  EN_BI = "en-BI",
  EN_BM = "en-BM",
  EN_BS = "en-BS",
  EN_BW = "en-BW",
  EN_BZ = "en-BZ",
  EN_CA = "en-CA",
  EN_CC = "en-CC",
  EN_CH = "en-CH",
  EN_CK = "en-CK",
  EN_CM = "en-CM",
  EN_CX = "en-CX",
  EN_CY = "en-CY",
  EN_DE = "en-DE",
  EN_DG = "en-DG",
  EN_DK = "en-DK",
  EN_DM = "en-DM",
  EN_DSRT = "en-Dsrt",
  EN_DSRT_US = "en-Dsrt-US",
  EN_ER = "en-ER",
  EN_FI = "en-FI",
  EN_FJ = "en-FJ",
  EN_FK = "en-FK",
  EN_FM = "en-FM",
  EN_GB = "en-GB",
  EN_GD = "en-GD",
  EN_GG = "en-GG",
  EN_GH = "en-GH",
  EN_GI = "en-GI",
  EN_GM = "en-GM",
  EN_GU = "en-GU",
  EN_GY = "en-GY",
  EN_HK = "en-HK",
  EN_ID = "en-ID",
  EN_IE = "en-IE",
  EN_IL = "en-IL",
  EN_IM = "en-IM",
  EN_IN = "en-IN",
  EN_IO = "en-IO",
  EN_JE = "en-JE",
  EN_JM = "en-JM",
  EN_KE = "en-KE",
  EN_KI = "en-KI",
  EN_KN = "en-KN",
  EN_KY = "en-KY",
  EN_LC = "en-LC",
  EN_LR = "en-LR",
  EN_LS = "en-LS",
  EN_MG = "en-MG",
  EN_MH = "en-MH",
  EN_MO = "en-MO",
  EN_MP = "en-MP",
  EN_MS = "en-MS",
  EN_MT = "en-MT",
  EN_MU = "en-MU",
  EN_MV = "en-MV",
  EN_MW = "en-MW",
  EN_MY = "en-MY",
  EN_NA = "en-NA",
  EN_NF = "en-NF",
  EN_NG = "en-NG",
  EN_NL = "en-NL",
  EN_NR = "en-NR",
  EN_NU = "en-NU",
  EN_NZ = "en-NZ",
  EN_PG = "en-PG",
  EN_PH = "en-PH",
  EN_PK = "en-PK",
  EN_PN = "en-PN",
  EN_PR = "en-PR",
  EN_PW = "en-PW",
  EN_RW = "en-RW",
  EN_SB = "en-SB",
  EN_SC = "en-SC",
  EN_SD = "en-SD",
  EN_SE = "en-SE",
  EN_SG = "en-SG",
  EN_SH = "en-SH",
  EN_SHAW = "en-Shaw",
  EN_SHAW_GB = "en-Shaw-GB",
  EN_SI = "en-SI",
  EN_SL = "en-SL",
  EN_SS = "en-SS",
  EN_SX = "en-SX",
  EN_SZ = "en-SZ",
  EN_TC = "en-TC",
  EN_TK = "en-TK",
  EN_TO = "en-TO",
  EN_TT = "en-TT",
  EN_TV = "en-TV",
  EN_TZ = "en-TZ",
  EN_UG = "en-UG",
  EN_UM = "en-UM",
  EN_US = "en-US",
  EN_US_POSIX = "en-US-POSIX",
  EN_VC = "en-VC",
  EN_VG = "en-VG",
  EN_VI = "en-VI",
  EN_VU = "en-VU",
  EN_WS = "en-WS",
  EN_ZA = "en-ZA",
  EN_ZM = "en-ZM",
  EN_ZW = "en-ZW",
  EO = "eo",
  EO_001 = "eo-001",
  ES = "es",
  ES_419 = "es-419",
  ES_AR = "es-AR",
  ES_BO = "es-BO",
  ES_BR = "es-BR",
  ES_BZ = "es-BZ",
  ES_CL = "es-CL",
  ES_CO = "es-CO",
  ES_CR = "es-CR",
  ES_CU = "es-CU",
  ES_DO = "es-DO",
  ES_EA = "es-EA",
  ES_EC = "es-EC",
  ES_ES = "es-ES",
  ES_GQ = "es-GQ",
  ES_GT = "es-GT",
  ES_HN = "es-HN",
  ES_IC = "es-IC",
  ES_MX = "es-MX",
  ES_NI = "es-NI",
  ES_PA = "es-PA",
  ES_PE = "es-PE",
  ES_PH = "es-PH",
  ES_PR = "es-PR",
  ES_PY = "es-PY",
  ES_SV = "es-SV",
  ES_US = "es-US",
  ES_UY = "es-UY",
  ES_VE = "es-VE",
  ET = "et",
  ET_EE = "et-EE",
  EU = "eu",
  EU_ES = "eu-ES",
  EWO = "ewo",
  EWO_CM = "ewo-CM",
  FA = "fa",
  FA_AF = "fa-AF",
  FA_IR = "fa-IR",
  FF = "ff",
  FF_ADLM = "ff-Adlm",
  FF_ADLM_BF = "ff-Adlm-BF",
  FF_ADLM_CM = "ff-Adlm-CM",
  FF_ADLM_GH = "ff-Adlm-GH",
  FF_ADLM_GM = "ff-Adlm-GM",
  FF_ADLM_GN = "ff-Adlm-GN",
  FF_ADLM_GW = "ff-Adlm-GW",
  FF_ADLM_LR = "ff-Adlm-LR",
  FF_ADLM_MR = "ff-Adlm-MR",
  FF_ADLM_NE = "ff-Adlm-NE",
  FF_ADLM_NG = "ff-Adlm-NG",
  FF_ADLM_SL = "ff-Adlm-SL",
  FF_ADLM_SN = "ff-Adlm-SN",
  FF_LATN = "ff-Latn",
  FF_LATN_BF = "ff-Latn-BF",
  FF_LATN_CM = "ff-Latn-CM",
  FF_LATN_GH = "ff-Latn-GH",
  FF_LATN_GM = "ff-Latn-GM",
  FF_LATN_GN = "ff-Latn-GN",
  FF_LATN_GW = "ff-Latn-GW",
  FF_LATN_LR = "ff-Latn-LR",
  FF_LATN_MR = "ff-Latn-MR",
  FF_LATN_NE = "ff-Latn-NE",
  FF_LATN_NG = "ff-Latn-NG",
  FF_LATN_SL = "ff-Latn-SL",
  FF_LATN_SN = "ff-Latn-SN",
  FI = "fi",
  FI_FI = "fi-FI",
  FIL = "fil",
  FIL_PH = "fil-PH",
  FO = "fo",
  FO_DK = "fo-DK",
  FO_FO = "fo-FO",
  FR = "fr",
  FR_BE = "fr-BE",
  FR_BF = "fr-BF",
  FR_BI = "fr-BI",
  FR_BJ = "fr-BJ",
  FR_BL = "fr-BL",
  FR_CA = "fr-CA",
  FR_CD = "fr-CD",
  FR_CF = "fr-CF",
  FR_CG = "fr-CG",
  FR_CH = "fr-CH",
  FR_CI = "fr-CI",
  FR_CM = "fr-CM",
  FR_DJ = "fr-DJ",
  FR_DZ = "fr-DZ",
  FR_FR = "fr-FR",
  FR_GA = "fr-GA",
  FR_GF = "fr-GF",
  FR_GN = "fr-GN",
  FR_GP = "fr-GP",
  FR_GQ = "fr-GQ",
  FR_HT = "fr-HT",
  FR_KM = "fr-KM",
  FR_LU = "fr-LU",
  FR_MA = "fr-MA",
  FR_MC = "fr-MC",
  FR_MF = "fr-MF",
  FR_MG = "fr-MG",
  FR_ML = "fr-ML",
  FR_MQ = "fr-MQ",
  FR_MR = "fr-MR",
  FR_MU = "fr-MU",
  FR_NC = "fr-NC",
  FR_NE = "fr-NE",
  FR_PF = "fr-PF",
  FR_PM = "fr-PM",
  FR_RE = "fr-RE",
  FR_RW = "fr-RW",
  FR_SC = "fr-SC",
  FR_SN = "fr-SN",
  FR_SY = "fr-SY",
  FR_TD = "fr-TD",
  FR_TG = "fr-TG",
  FR_TN = "fr-TN",
  FR_VU = "fr-VU",
  FR_WF = "fr-WF",
  FR_YT = "fr-YT",
  FRR = "frr",
  FRR_DE = "frr-DE",
  FUR = "fur",
  FUR_IT = "fur-IT",
  FY = "fy",
  FY_NL = "fy-NL",
  GA = "ga",
  GA_GB = "ga-GB",
  GA_IE = "ga-IE",
  GAA = "gaa",
  GAA_GH = "gaa-GH",
  GD = "gd",
  GD_GB = "gd-GB",
  GEZ = "gez",
  GEZ_ER = "gez-ER",
  GEZ_ET = "gez-ET",
  GL = "gl",
  GL_ES = "gl-ES",
  GN = "gn",
  GN_PY = "gn-PY",
  GSW = "gsw",
  GSW_CH = "gsw-CH",
  GSW_FR = "gsw-FR",
  GSW_LI = "gsw-LI",
  GU = "gu",
  GU_IN = "gu-IN",
  GUZ = "guz",
  GUZ_KE = "guz-KE",
  GV = "gv",
  GV_IM = "gv-IM",
  HA = "ha",
  HA_ARAB = "ha-Arab",
  HA_ARAB_NG = "ha-Arab-NG",
  HA_ARAB_SD = "ha-Arab-SD",
  HA_GH = "ha-GH",
  HA_NE = "ha-NE",
  HA_NG = "ha-NG",
  HAW = "haw",
  HAW_US = "haw-US",
  HE = "he",
  HE_IL = "he-IL",
  HI = "hi",
  HI_IN = "hi-IN",
  HI_LATN = "hi-Latn",
  HI_LATN_IN = "hi-Latn-IN",
  HNJ = "hnj",
  HNJ_HMNP = "hnj-Hmnp",
  HNJ_HMNP_US = "hnj-Hmnp-US",
  HR = "hr",
  HR_BA = "hr-BA",
  HR_HR = "hr-HR",
  HSB = "hsb",
  HSB_DE = "hsb-DE",
  HU = "hu",
  HU_HU = "hu-HU",
  HY = "hy",
  HY_AM = "hy-AM",
  IA = "ia",
  IA_001 = "ia-001",
  ID = "id",
  ID_ID = "id-ID",
  IE = "ie",
  IE_EE = "ie-EE",
  IG = "ig",
  IG_NG = "ig-NG",
  II = "ii",
  II_CN = "ii-CN",
  IO = "io",
  IO_001 = "io-001",
  IS = "is",
  IS_IS = "is-IS",
  IT = "it",
  IT_CH = "it-CH",
  IT_IT = "it-IT",
  IT_SM = "it-SM",
  IT_VA = "it-VA",
  IU = "iu",
  IU_CA = "iu-CA",
  IU_LATN = "iu-Latn",
  IU_LATN_CA = "iu-Latn-CA",
  JA = "ja",
  JA_JP = "ja-JP",
  JBO = "jbo",
  JBO_001 = "jbo-001",
  JGO = "jgo",
  JGO_CM = "jgo-CM",
  JMC = "jmc",
  JMC_TZ = "jmc-TZ",
  JV = "jv",
  JV_ID = "jv-ID",
  KA = "ka",
  KA_GE = "ka-GE",
  KAA = "kaa",
  KAA_CYRL = "kaa-Cyrl",
  KAA_CYRL_UZ = "kaa-Cyrl-UZ",
  KAA_LATN = "kaa-Latn",
  KAA_LATN_UZ = "kaa-Latn-UZ",
  KAB = "kab",
  KAB_DZ = "kab-DZ",
  KAJ = "kaj",
  KAJ_NG = "kaj-NG",
  KAM = "kam",
  KAM_KE = "kam-KE",
  KCG = "kcg",
  KCG_NG = "kcg-NG",
  KDE = "kde",
  KDE_TZ = "kde-TZ",
  KEA = "kea",
  KEA_CV = "kea-CV",
  KEN = "ken",
  KEN_CM = "ken-CM",
  KGP = "kgp",
  KGP_BR = "kgp-BR",
  KHQ = "khq",
  KHQ_ML = "khq-ML",
  KI = "ki",
  KI_KE = "ki-KE",
  KK = "kk",
  KK_ARAB = "kk-Arab",
  KK_ARAB_CN = "kk-Arab-CN",
  KK_CYRL = "kk-Cyrl",
  KK_CYRL_KZ = "kk-Cyrl-KZ",
  KK_KZ = "kk-KZ",
  KKJ = "kkj",
  KKJ_CM = "kkj-CM",
  KL = "kl",
  KL_GL = "kl-GL",
  KLN = "kln",
  KLN_KE = "kln-KE",
  KM = "km",
  KM_KH = "km-KH",
  KN = "kn",
  KN_IN = "kn-IN",
  KO = "ko",
  KO_CN = "ko-CN",
  KO_KP = "ko-KP",
  KO_KR = "ko-KR",
  KOK = "kok",
  KOK_DEVA = "kok-Deva",
  KOK_DEVA_IN = "kok-Deva-IN",
  KOK_LATN = "kok-Latn",
  KOK_LATN_IN = "kok-Latn-IN",
  KPE = "kpe",
  KPE_GN = "kpe-GN",
  KPE_LR = "kpe-LR",
  KS = "ks",
  KS_ARAB = "ks-Arab",
  KS_ARAB_IN = "ks-Arab-IN",
  KS_DEVA = "ks-Deva",
  KS_DEVA_IN = "ks-Deva-IN",
  KSB = "ksb",
  KSB_TZ = "ksb-TZ",
  KSF = "ksf",
  KSF_CM = "ksf-CM",
  KSH = "ksh",
  KSH_DE = "ksh-DE",
  KU = "ku",
  KU_TR = "ku-TR",
  KW = "kw",
  KW_GB = "kw-GB",
  KXV = "kxv",
  KXV_DEVA = "kxv-Deva",
  KXV_DEVA_IN = "kxv-Deva-IN",
  KXV_LATN = "kxv-Latn",
  KXV_LATN_IN = "kxv-Latn-IN",
  KXV_ORYA = "kxv-Orya",
  KXV_ORYA_IN = "kxv-Orya-IN",
  KXV_TELU = "kxv-Telu",
  KXV_TELU_IN = "kxv-Telu-IN",
  KY = "ky",
  KY_KG = "ky-KG",
  LA = "la",
  LA_VA = "la-VA",
  LAG = "lag",
  LAG_TZ = "lag-TZ",
  LB = "lb",
  LB_LU = "lb-LU",
  LG = "lg",
  LG_UG = "lg-UG",
  LIJ = "lij",
  LIJ_IT = "lij-IT",
  LKT = "lkt",
  LKT_US = "lkt-US",
  LLD = "lld",
  LLD_IT = "lld-IT",
  LMO = "lmo",
  LMO_IT = "lmo-IT",
  LN = "ln",
  LN_AO = "ln-AO",
  LN_CD = "ln-CD",
  LN_CF = "ln-CF",
  LN_CG = "ln-CG",
  LO = "lo",
  LO_LA = "lo-LA",
  LRC = "lrc",
  LRC_IQ = "lrc-IQ",
  LRC_IR = "lrc-IR",
  LT = "lt",
  LT_LT = "lt-LT",
  LTG = "ltg",
  LTG_LV = "ltg-LV",
  LU = "lu",
  LU_CD = "lu-CD",
  LUO = "luo",
  LUO_KE = "luo-KE",
  LUY = "luy",
  LUY_KE = "luy-KE",
  LV = "lv",
  LV_LV = "lv-LV",
  MAI = "mai",
  MAI_IN = "mai-IN",
  MAS = "mas",
  MAS_KE = "mas-KE",
  MAS_TZ = "mas-TZ",
  MDF = "mdf",
  MDF_RU = "mdf-RU",
  MER = "mer",
  MER_KE = "mer-KE",
  MFE = "mfe",
  MFE_MU = "mfe-MU",
  MG = "mg",
  MG_MG = "mg-MG",
  MGH = "mgh",
  MGH_MZ = "mgh-MZ",
  MGO = "mgo",
  MGO_CM = "mgo-CM",
  MHN = "mhn",
  MHN_IT = "mhn-IT",
  MI = "mi",
  MI_NZ = "mi-NZ",
  MIC = "mic",
  MIC_CA = "mic-CA",
  MK = "mk",
  MK_MK = "mk-MK",
  ML = "ml",
  ML_IN = "ml-IN",
  MN = "mn",
  MN_MN = "mn-MN",
  MN_MONG = "mn-Mong",
  MN_MONG_CN = "mn-Mong-CN",
  MN_MONG_MN = "mn-Mong-MN",
  MNI = "mni",
  MNI_BENG = "mni-Beng",
  MNI_BENG_IN = "mni-Beng-IN",
  MNI_MTEI = "mni-Mtei",
  MNI_MTEI_IN = "mni-Mtei-IN",
  MOH = "moh",
  MOH_CA = "moh-CA",
  MR = "mr",
  MR_IN = "mr-IN",
  MS = "ms",
  MS_ARAB = "ms-Arab",
  MS_ARAB_BN = "ms-Arab-BN",
  MS_ARAB_MY = "ms-Arab-MY",
  MS_BN = "ms-BN",
  MS_ID = "ms-ID",
  MS_MY = "ms-MY",
  MS_SG = "ms-SG",
  MT = "mt",
  MT_MT = "mt-MT",
  MUA = "mua",
  MUA_CM = "mua-CM",
  MUS = "mus",
  MUS_US = "mus-US",
  MY = "my",
  MY_MM = "my-MM",
  MYV = "myv",
  MYV_RU = "myv-RU",
  MZN = "mzn",
  MZN_IR = "mzn-IR",
  NAQ = "naq",
  NAQ_NA = "naq-NA",
  NB = "nb",
  NB_NO = "nb-NO",
  NB_SJ = "nb-SJ",
  ND = "nd",
  ND_ZW = "nd-ZW",
  NDS = "nds",
  NDS_DE = "nds-DE",
  NDS_NL = "nds-NL",
  NE = "ne",
  NE_IN = "ne-IN",
  NE_NP = "ne-NP",
  NL = "nl",
  NL_AW = "nl-AW",
  NL_BE = "nl-BE",
  NL_BQ = "nl-BQ",
  NL_CW = "nl-CW",
  NL_NL = "nl-NL",
  NL_SR = "nl-SR",
  NL_SX = "nl-SX",
  NMG = "nmg",
  NMG_CM = "nmg-CM",
  NN = "nn",
  NN_NO = "nn-NO",
  NNH = "nnh",
  NNH_CM = "nnh-CM",
  NO = "no",
  NQO = "nqo",
  NQO_GN = "nqo-GN",
  NR = "nr",
  NR_ZA = "nr-ZA",
  NSO = "nso",
  NSO_ZA = "nso-ZA",
  NUS = "nus",
  NUS_SS = "nus-SS",
  NV = "nv",
  NV_US = "nv-US",
  NY = "ny",
  NY_MW = "ny-MW",
  NYN = "nyn",
  NYN_UG = "nyn-UG",
  OC = "oc",
  OC_ES = "oc-ES",
  OC_FR = "oc-FR",
  OM = "om",
  OM_ET = "om-ET",
  OM_KE = "om-KE",
  OR = "or",
  OR_IN = "or-IN",
  OS = "os",
  OS_GE = "os-GE",
  OS_RU = "os-RU",
  OSA = "osa",
  OSA_US = "osa-US",
  PA = "pa",
  PA_ARAB = "pa-Arab",
  PA_ARAB_PK = "pa-Arab-PK",
  PA_GURU = "pa-Guru",
  PA_GURU_IN = "pa-Guru-IN",
  PAP = "pap",
  PAP_AW = "pap-AW",
  PAP_CW = "pap-CW",
  PCM = "pcm",
  PCM_NG = "pcm-NG",
  PIS = "pis",
  PIS_SB = "pis-SB",
  PL = "pl",
  PL_PL = "pl-PL",
  PRG = "prg",
  PRG_PL = "prg-PL",
  PS = "ps",
  PS_AF = "ps-AF",
  PS_PK = "ps-PK",
  PT = "pt",
  PT_AO = "pt-AO",
  PT_BR = "pt-BR",
  PT_CH = "pt-CH",
  PT_CV = "pt-CV",
  PT_GQ = "pt-GQ",
  PT_GW = "pt-GW",
  PT_LU = "pt-LU",
  PT_MO = "pt-MO",
  PT_MZ = "pt-MZ",
  PT_PT = "pt-PT",
  PT_ST = "pt-ST",
  PT_TL = "pt-TL",
  QU = "qu",
  QU_BO = "qu-BO",
  QU_EC = "qu-EC",
  QU_PE = "qu-PE",
  QUC = "quc",
  QUC_GT = "quc-GT",
  RAJ = "raj",
  RAJ_IN = "raj-IN",
  RHG = "rhg",
  RHG_ROHG = "rhg-Rohg",
  RHG_ROHG_BD = "rhg-Rohg-BD",
  RHG_ROHG_MM = "rhg-Rohg-MM",
  RIF = "rif",
  RIF_MA = "rif-MA",
  RM = "rm",
  RM_CH = "rm-CH",
  RN = "rn",
  RN_BI = "rn-BI",
  RO = "ro",
  RO_MD = "ro-MD",
  RO_RO = "ro-RO",
  ROF = "rof",
  ROF_TZ = "rof-TZ",
  ROOT = "root",
  RU = "ru",
  RU_BY = "ru-BY",
  RU_KG = "ru-KG",
  RU_KZ = "ru-KZ",
  RU_MD = "ru-MD",
  RU_RU = "ru-RU",
  RU_UA = "ru-UA",
  RW = "rw",
  RW_RW = "rw-RW",
  RWK = "rwk",
  RWK_TZ = "rwk-TZ",
  SA = "sa",
  SA_IN = "sa-IN",
  SAH = "sah",
  SAH_RU = "sah-RU",
  SAQ = "saq",
  SAQ_KE = "saq-KE",
  SAT = "sat",
  SAT_DEVA = "sat-Deva",
  SAT_DEVA_IN = "sat-Deva-IN",
  SAT_OLCK = "sat-Olck",
  SAT_OLCK_IN = "sat-Olck-IN",
  SBP = "sbp",
  SBP_TZ = "sbp-TZ",
  SC = "sc",
  SC_IT = "sc-IT",
  SCN = "scn",
  SCN_IT = "scn-IT",
  SD = "sd",
  SD_ARAB = "sd-Arab",
  SD_ARAB_PK = "sd-Arab-PK",
  SD_DEVA = "sd-Deva",
  SD_DEVA_IN = "sd-Deva-IN",
  SDH = "sdh",
  SDH_IQ = "sdh-IQ",
  SDH_IR = "sdh-IR",
  SE = "se",
  SE_FI = "se-FI",
  SE_NO = "se-NO",
  SE_SE = "se-SE",
  SEH = "seh",
  SEH_MZ = "seh-MZ",
  SES = "ses",
  SES_ML = "ses-ML",
  SG = "sg",
  SG_CF = "sg-CF",
  SHI = "shi",
  SHI_LATN = "shi-Latn",
  SHI_LATN_MA = "shi-Latn-MA",
  SHI_TFNG = "shi-Tfng",
  SHI_TFNG_MA = "shi-Tfng-MA",
  SHN = "shn",
  SHN_MM = "shn-MM",
  SHN_TH = "shn-TH",
  SI = "si",
  SI_LK = "si-LK",
  SID = "sid",
  SID_ET = "sid-ET",
  SK = "sk",
  SK_SK = "sk-SK",
  SKR = "skr",
  SKR_PK = "skr-PK",
  SL = "sl",
  SL_SI = "sl-SI",
  SMA = "sma",
  SMA_NO = "sma-NO",
  SMA_SE = "sma-SE",
  SMJ = "smj",
  SMJ_NO = "smj-NO",
  SMJ_SE = "smj-SE",
  SMN = "smn",
  SMN_FI = "smn-FI",
  SMS = "sms",
  SMS_FI = "sms-FI",
  SN = "sn",
  SN_ZW = "sn-ZW",
  SO = "so",
  SO_DJ = "so-DJ",
  SO_ET = "so-ET",
  SO_KE = "so-KE",
  SO_SO = "so-SO",
  SQ = "sq",
  SQ_AL = "sq-AL",
  SQ_MK = "sq-MK",
  SQ_XK = "sq-XK",
  SR = "sr",
  SR_CYRL = "sr-Cyrl",
  SR_CYRL_BA = "sr-Cyrl-BA",
  SR_CYRL_ME = "sr-Cyrl-ME",
  SR_CYRL_RS = "sr-Cyrl-RS",
  SR_CYRL_XK = "sr-Cyrl-XK",
  SR_LATN = "sr-Latn",
  SR_LATN_BA = "sr-Latn-BA",
  SR_LATN_ME = "sr-Latn-ME",
  SR_LATN_RS = "sr-Latn-RS",
  SR_LATN_XK = "sr-Latn-XK",
  SS = "ss",
  SS_SZ = "ss-SZ",
  SS_ZA = "ss-ZA",
  SSY = "ssy",
  SSY_ER = "ssy-ER",
  ST = "st",
  ST_LS = "st-LS",
  ST_ZA = "st-ZA",
  SU = "su",
  SU_LATN = "su-Latn",
  SU_LATN_ID = "su-Latn-ID",
  SV = "sv",
  SV_AX = "sv-AX",
  SV_FI = "sv-FI",
  SV_SE = "sv-SE",
  SW = "sw",
  SW_CD = "sw-CD",
  SW_KE = "sw-KE",
  SW_TZ = "sw-TZ",
  SW_UG = "sw-UG",
  SYR = "syr",
  SYR_IQ = "syr-IQ",
  SYR_SY = "syr-SY",
  SZL = "szl",
  SZL_PL = "szl-PL",
  TA = "ta",
  TA_IN = "ta-IN",
  TA_LK = "ta-LK",
  TA_MY = "ta-MY",
  TA_SG = "ta-SG",
  TE = "te",
  TE_IN = "te-IN",
  TEO = "teo",
  TEO_KE = "teo-KE",
  TEO_UG = "teo-UG",
  TG = "tg",
  TG_TJ = "tg-TJ",
  TH = "th",
  TH_TH = "th-TH",
  TI = "ti",
  TI_ER = "ti-ER",
  TI_ET = "ti-ET",
  TIG = "tig",
  TIG_ER = "tig-ER",
  TK = "tk",
  TK_TM = "tk-TM",
  TN = "tn",
  TN_BW = "tn-BW",
  TN_ZA = "tn-ZA",
  TO = "to",
  TO_TO = "to-TO",
  TOK = "tok",
  TOK_001 = "tok-001",
  TPI = "tpi",
  TPI_PG = "tpi-PG",
  TR = "tr",
  TR_CY = "tr-CY",
  TR_TR = "tr-TR",
  TRV = "trv",
  TRV_TW = "trv-TW",
  TRW = "trw",
  TRW_PK = "trw-PK",
  TS = "ts",
  TS_ZA = "ts-ZA",
  TT = "tt",
  TT_RU = "tt-RU",
  TWQ = "twq",
  TWQ_NE = "twq-NE",
  TYV = "tyv",
  TYV_RU = "tyv-RU",
  TZM = "tzm",
  TZM_MA = "tzm-MA",
  UG = "ug",
  UG_CN = "ug-CN",
  UK = "uk",
  UK_UA = "uk-UA",
  UR = "ur",
  UR_IN = "ur-IN",
  UR_PK = "ur-PK",
  UZ = "uz",
  UZ_ARAB = "uz-Arab",
  UZ_ARAB_AF = "uz-Arab-AF",
  UZ_CYRL = "uz-Cyrl",
  UZ_CYRL_UZ = "uz-Cyrl-UZ",
  UZ_LATN = "uz-Latn",
  UZ_LATN_UZ = "uz-Latn-UZ",
  VAI = "vai",
  VAI_LATN = "vai-Latn",
  VAI_LATN_LR = "vai-Latn-LR",
  VAI_VAII = "vai-Vaii",
  VAI_VAII_LR = "vai-Vaii-LR",
  VE = "ve",
  VE_ZA = "ve-ZA",
  VEC = "vec",
  VEC_IT = "vec-IT",
  VI = "vi",
  VI_VN = "vi-VN",
  VMW = "vmw",
  VMW_MZ = "vmw-MZ",
  VO = "vo",
  VO_001 = "vo-001",
  VUN = "vun",
  VUN_TZ = "vun-TZ",
  WA = "wa",
  WA_BE = "wa-BE",
  WAE = "wae",
  WAE_CH = "wae-CH",
  WAL = "wal",
  WAL_ET = "wal-ET",
  WBP = "wbp",
  WBP_AU = "wbp-AU",
  WO = "wo",
  WO_SN = "wo-SN",
  XH = "xh",
  XH_ZA = "xh-ZA",
  XNR = "xnr",
  XNR_IN = "xnr-IN",
  XOG = "xog",
  XOG_UG = "xog-UG",
  YAV = "yav",
  YAV_CM = "yav-CM",
  YI = "yi",
  YI_UA = "yi-UA",
  YO = "yo",
  YO_BJ = "yo-BJ",
  YO_NG = "yo-NG",
  YRL = "yrl",
  YRL_BR = "yrl-BR",
  YRL_CO = "yrl-CO",
  YRL_VE = "yrl-VE",
  YUE = "yue",
  YUE_HANS = "yue-Hans",
  YUE_HANS_CN = "yue-Hans-CN",
  YUE_HANT = "yue-Hant",
  YUE_HANT_CN = "yue-Hant-CN",
  YUE_HANT_HK = "yue-Hant-HK",
  ZA = "za",
  ZA_CN = "za-CN",
  ZGH = "zgh",
  ZGH_MA = "zgh-MA",
  ZH = "zh",
  ZH_HANS = "zh-Hans",
  ZH_HANS_CN = "zh-Hans-CN",
  ZH_HANS_HK = "zh-Hans-HK",
  ZH_HANS_MO = "zh-Hans-MO",
  ZH_HANS_MY = "zh-Hans-MY",
  ZH_HANS_SG = "zh-Hans-SG",
  ZH_HANT = "zh-Hant",
  ZH_HANT_HK = "zh-Hant-HK",
  ZH_HANT_MO = "zh-Hant-MO",
  ZH_HANT_MY = "zh-Hant-MY",
  ZH_HANT_TW = "zh-Hant-TW",
  ZH_LATN = "zh-Latn",
  ZH_LATN_CN = "zh-Latn-CN",
  ZU = "zu",
  ZU_ZA = "zu-ZA",
}

export const languages = [
  LanguageCode.AA,
  LanguageCode.AA_DJ,
  LanguageCode.AA_ER,
  LanguageCode.AA_ET,
  LanguageCode.AB,
  LanguageCode.AB_GE,
  LanguageCode.AF,
  LanguageCode.AF_NA,
  LanguageCode.AF_ZA,
  LanguageCode.AGQ,
  LanguageCode.AGQ_CM,
  LanguageCode.AK,
  LanguageCode.AK_GH,
  LanguageCode.AM,
  LanguageCode.AM_ET,
  LanguageCode.AN,
  LanguageCode.AN_ES,
  LanguageCode.ANN,
  LanguageCode.ANN_NG,
  LanguageCode.APC,
  LanguageCode.APC_SY,
  LanguageCode.AR,
  LanguageCode.AR_001,
  LanguageCode.AR_AE,
  LanguageCode.AR_BH,
  LanguageCode.AR_DJ,
  LanguageCode.AR_DZ,
  LanguageCode.AR_EG,
  LanguageCode.AR_EH,
  LanguageCode.AR_ER,
  LanguageCode.AR_IL,
  LanguageCode.AR_IQ,
  LanguageCode.AR_JO,
  LanguageCode.AR_KM,
  LanguageCode.AR_KW,
  LanguageCode.AR_LB,
  LanguageCode.AR_LY,
  LanguageCode.AR_MA,
  LanguageCode.AR_MR,
  LanguageCode.AR_OM,
  LanguageCode.AR_PS,
  LanguageCode.AR_QA,
  LanguageCode.AR_SA,
  LanguageCode.AR_SD,
  LanguageCode.AR_SO,
  LanguageCode.AR_SS,
  LanguageCode.AR_SY,
  LanguageCode.AR_TD,
  LanguageCode.AR_TN,
  LanguageCode.AR_YE,
  LanguageCode.ARN,
  LanguageCode.ARN_CL,
  LanguageCode.AS,
  LanguageCode.AS_IN,
  LanguageCode.ASA,
  LanguageCode.ASA_TZ,
  LanguageCode.AST,
  LanguageCode.AST_ES,
  LanguageCode.AZ,
  LanguageCode.AZ_ARAB,
  LanguageCode.AZ_ARAB_IQ,
  LanguageCode.AZ_ARAB_IR,
  LanguageCode.AZ_ARAB_TR,
  LanguageCode.AZ_CYRL,
  LanguageCode.AZ_CYRL_AZ,
  LanguageCode.AZ_LATN,
  LanguageCode.AZ_LATN_AZ,
  LanguageCode.BA,
  LanguageCode.BA_RU,
  LanguageCode.BAL,
  LanguageCode.BAL_ARAB,
  LanguageCode.BAL_ARAB_PK,
  LanguageCode.BAL_LATN,
  LanguageCode.BAL_LATN_PK,
  LanguageCode.BAS,
  LanguageCode.BAS_CM,
  LanguageCode.BE,
  LanguageCode.BE_BY,
  LanguageCode.BE_TARASK,
  LanguageCode.BEM,
  LanguageCode.BEM_ZM,
  LanguageCode.BEW,
  LanguageCode.BEW_ID,
  LanguageCode.BEZ,
  LanguageCode.BEZ_TZ,
  LanguageCode.BG,
  LanguageCode.BG_BG,
  LanguageCode.BGC,
  LanguageCode.BGC_IN,
  LanguageCode.BGN,
  LanguageCode.BGN_AE,
  LanguageCode.BGN_AF,
  LanguageCode.BGN_IR,
  LanguageCode.BGN_OM,
  LanguageCode.BGN_PK,
  LanguageCode.BHO,
  LanguageCode.BHO_IN,
  LanguageCode.BLO,
  LanguageCode.BLO_BJ,
  LanguageCode.BLT,
  LanguageCode.BLT_VN,
  LanguageCode.BM,
  LanguageCode.BM_ML,
  LanguageCode.BM_NKOO,
  LanguageCode.BM_NKOO_ML,
  LanguageCode.BN,
  LanguageCode.BN_BD,
  LanguageCode.BN_IN,
  LanguageCode.BO,
  LanguageCode.BO_CN,
  LanguageCode.BO_IN,
  LanguageCode.BR,
  LanguageCode.BR_FR,
  LanguageCode.BRX,
  LanguageCode.BRX_IN,
  LanguageCode.BS,
  LanguageCode.BS_CYRL,
  LanguageCode.BS_CYRL_BA,
  LanguageCode.BS_LATN,
  LanguageCode.BS_LATN_BA,
  LanguageCode.BSS,
  LanguageCode.BSS_CM,
  LanguageCode.BYN,
  LanguageCode.BYN_ER,
  LanguageCode.CA,
  LanguageCode.CA_AD,
  LanguageCode.CA_ES,
  LanguageCode.CA_ES_VALENCIA,
  LanguageCode.CA_FR,
  LanguageCode.CA_IT,
  LanguageCode.CAD,
  LanguageCode.CAD_US,
  LanguageCode.CCH,
  LanguageCode.CCH_NG,
  LanguageCode.CCP,
  LanguageCode.CCP_BD,
  LanguageCode.CCP_IN,
  LanguageCode.CE,
  LanguageCode.CE_RU,
  LanguageCode.CEB,
  LanguageCode.CEB_PH,
  LanguageCode.CGG,
  LanguageCode.CGG_UG,
  LanguageCode.CHO,
  LanguageCode.CHO_US,
  LanguageCode.CHR,
  LanguageCode.CHR_US,
  LanguageCode.CIC,
  LanguageCode.CIC_US,
  LanguageCode.CKB,
  LanguageCode.CKB_IQ,
  LanguageCode.CKB_IR,
  LanguageCode.CO,
  LanguageCode.CO_FR,
  LanguageCode.CS,
  LanguageCode.CS_CZ,
  LanguageCode.CSW,
  LanguageCode.CSW_CA,
  LanguageCode.CU,
  LanguageCode.CU_RU,
  LanguageCode.CV,
  LanguageCode.CV_RU,
  LanguageCode.CY,
  LanguageCode.CY_GB,
  LanguageCode.DA,
  LanguageCode.DA_DK,
  LanguageCode.DA_GL,
  LanguageCode.DAV,
  LanguageCode.DAV_KE,
  LanguageCode.DE,
  LanguageCode.DE_AT,
  LanguageCode.DE_BE,
  LanguageCode.DE_CH,
  LanguageCode.DE_DE,
  LanguageCode.DE_IT,
  LanguageCode.DE_LI,
  LanguageCode.DE_LU,
  LanguageCode.DJE,
  LanguageCode.DJE_NE,
  LanguageCode.DOI,
  LanguageCode.DOI_IN,
  LanguageCode.DSB,
  LanguageCode.DSB_DE,
  LanguageCode.DUA,
  LanguageCode.DUA_CM,
  LanguageCode.DV,
  LanguageCode.DV_MV,
  LanguageCode.DYO,
  LanguageCode.DYO_SN,
  LanguageCode.DZ,
  LanguageCode.DZ_BT,
  LanguageCode.EBU,
  LanguageCode.EBU_KE,
  LanguageCode.EE,
  LanguageCode.EE_GH,
  LanguageCode.EE_TG,
  LanguageCode.EL,
  LanguageCode.EL_CY,
  LanguageCode.EL_GR,
  LanguageCode.EL_POLYTON,
  LanguageCode.EN,
  LanguageCode.EN_001,
  LanguageCode.EN_150,
  LanguageCode.EN_AE,
  LanguageCode.EN_AG,
  LanguageCode.EN_AI,
  LanguageCode.EN_AS,
  LanguageCode.EN_AT,
  LanguageCode.EN_AU,
  LanguageCode.EN_BB,
  LanguageCode.EN_BE,
  LanguageCode.EN_BI,
  LanguageCode.EN_BM,
  LanguageCode.EN_BS,
  LanguageCode.EN_BW,
  LanguageCode.EN_BZ,
  LanguageCode.EN_CA,
  LanguageCode.EN_CC,
  LanguageCode.EN_CH,
  LanguageCode.EN_CK,
  LanguageCode.EN_CM,
  LanguageCode.EN_CX,
  LanguageCode.EN_CY,
  LanguageCode.EN_DE,
  LanguageCode.EN_DG,
  LanguageCode.EN_DK,
  LanguageCode.EN_DM,
  LanguageCode.EN_DSRT,
  LanguageCode.EN_DSRT_US,
  LanguageCode.EN_ER,
  LanguageCode.EN_FI,
  LanguageCode.EN_FJ,
  LanguageCode.EN_FK,
  LanguageCode.EN_FM,
  LanguageCode.EN_GB,
  LanguageCode.EN_GD,
  LanguageCode.EN_GG,
  LanguageCode.EN_GH,
  LanguageCode.EN_GI,
  LanguageCode.EN_GM,
  LanguageCode.EN_GU,
  LanguageCode.EN_GY,
  LanguageCode.EN_HK,
  LanguageCode.EN_ID,
  LanguageCode.EN_IE,
  LanguageCode.EN_IL,
  LanguageCode.EN_IM,
  LanguageCode.EN_IN,
  LanguageCode.EN_IO,
  LanguageCode.EN_JE,
  LanguageCode.EN_JM,
  LanguageCode.EN_KE,
  LanguageCode.EN_KI,
  LanguageCode.EN_KN,
  LanguageCode.EN_KY,
  LanguageCode.EN_LC,
  LanguageCode.EN_LR,
  LanguageCode.EN_LS,
  LanguageCode.EN_MG,
  LanguageCode.EN_MH,
  LanguageCode.EN_MO,
  LanguageCode.EN_MP,
  LanguageCode.EN_MS,
  LanguageCode.EN_MT,
  LanguageCode.EN_MU,
  LanguageCode.EN_MV,
  LanguageCode.EN_MW,
  LanguageCode.EN_MY,
  LanguageCode.EN_NA,
  LanguageCode.EN_NF,
  LanguageCode.EN_NG,
  LanguageCode.EN_NL,
  LanguageCode.EN_NR,
  LanguageCode.EN_NU,
  LanguageCode.EN_NZ,
  LanguageCode.EN_PG,
  LanguageCode.EN_PH,
  LanguageCode.EN_PK,
  LanguageCode.EN_PN,
  LanguageCode.EN_PR,
  LanguageCode.EN_PW,
  LanguageCode.EN_RW,
  LanguageCode.EN_SB,
  LanguageCode.EN_SC,
  LanguageCode.EN_SD,
  LanguageCode.EN_SE,
  LanguageCode.EN_SG,
  LanguageCode.EN_SH,
  LanguageCode.EN_SHAW,
  LanguageCode.EN_SHAW_GB,
  LanguageCode.EN_SI,
  LanguageCode.EN_SL,
  LanguageCode.EN_SS,
  LanguageCode.EN_SX,
  LanguageCode.EN_SZ,
  LanguageCode.EN_TC,
  LanguageCode.EN_TK,
  LanguageCode.EN_TO,
  LanguageCode.EN_TT,
  LanguageCode.EN_TV,
  LanguageCode.EN_TZ,
  LanguageCode.EN_UG,
  LanguageCode.EN_UM,
  LanguageCode.EN_US,
  LanguageCode.EN_US_POSIX,
  LanguageCode.EN_VC,
  LanguageCode.EN_VG,
  LanguageCode.EN_VI,
  LanguageCode.EN_VU,
  LanguageCode.EN_WS,
  LanguageCode.EN_ZA,
  LanguageCode.EN_ZM,
  LanguageCode.EN_ZW,
  LanguageCode.EO,
  LanguageCode.EO_001,
  LanguageCode.ES,
  LanguageCode.ES_419,
  LanguageCode.ES_AR,
  LanguageCode.ES_BO,
  LanguageCode.ES_BR,
  LanguageCode.ES_BZ,
  LanguageCode.ES_CL,
  LanguageCode.ES_CO,
  LanguageCode.ES_CR,
  LanguageCode.ES_CU,
  LanguageCode.ES_DO,
  LanguageCode.ES_EA,
  LanguageCode.ES_EC,
  LanguageCode.ES_ES,
  LanguageCode.ES_GQ,
  LanguageCode.ES_GT,
  LanguageCode.ES_HN,
  LanguageCode.ES_IC,
  LanguageCode.ES_MX,
  LanguageCode.ES_NI,
  LanguageCode.ES_PA,
  LanguageCode.ES_PE,
  LanguageCode.ES_PH,
  LanguageCode.ES_PR,
  LanguageCode.ES_PY,
  LanguageCode.ES_SV,
  LanguageCode.ES_US,
  LanguageCode.ES_UY,
  LanguageCode.ES_VE,
  LanguageCode.ET,
  LanguageCode.ET_EE,
  LanguageCode.EU,
  LanguageCode.EU_ES,
  LanguageCode.EWO,
  LanguageCode.EWO_CM,
  LanguageCode.FA,
  LanguageCode.FA_AF,
  LanguageCode.FA_IR,
  LanguageCode.FF,
  LanguageCode.FF_ADLM,
  LanguageCode.FF_ADLM_BF,
  LanguageCode.FF_ADLM_CM,
  LanguageCode.FF_ADLM_GH,
  LanguageCode.FF_ADLM_GM,
  LanguageCode.FF_ADLM_GN,
  LanguageCode.FF_ADLM_GW,
  LanguageCode.FF_ADLM_LR,
  LanguageCode.FF_ADLM_MR,
  LanguageCode.FF_ADLM_NE,
  LanguageCode.FF_ADLM_NG,
  LanguageCode.FF_ADLM_SL,
  LanguageCode.FF_ADLM_SN,
  LanguageCode.FF_LATN,
  LanguageCode.FF_LATN_BF,
  LanguageCode.FF_LATN_CM,
  LanguageCode.FF_LATN_GH,
  LanguageCode.FF_LATN_GM,
  LanguageCode.FF_LATN_GN,
  LanguageCode.FF_LATN_GW,
  LanguageCode.FF_LATN_LR,
  LanguageCode.FF_LATN_MR,
  LanguageCode.FF_LATN_NE,
  LanguageCode.FF_LATN_NG,
  LanguageCode.FF_LATN_SL,
  LanguageCode.FF_LATN_SN,
  LanguageCode.FI,
  LanguageCode.FI_FI,
  LanguageCode.FIL,
  LanguageCode.FIL_PH,
  LanguageCode.FO,
  LanguageCode.FO_DK,
  LanguageCode.FO_FO,
  LanguageCode.FR,
  LanguageCode.FR_BE,
  LanguageCode.FR_BF,
  LanguageCode.FR_BI,
  LanguageCode.FR_BJ,
  LanguageCode.FR_BL,
  LanguageCode.FR_CA,
  LanguageCode.FR_CD,
  LanguageCode.FR_CF,
  LanguageCode.FR_CG,
  LanguageCode.FR_CH,
  LanguageCode.FR_CI,
  LanguageCode.FR_CM,
  LanguageCode.FR_DJ,
  LanguageCode.FR_DZ,
  LanguageCode.FR_FR,
  LanguageCode.FR_GA,
  LanguageCode.FR_GF,
  LanguageCode.FR_GN,
  LanguageCode.FR_GP,
  LanguageCode.FR_GQ,
  LanguageCode.FR_HT,
  LanguageCode.FR_KM,
  LanguageCode.FR_LU,
  LanguageCode.FR_MA,
  LanguageCode.FR_MC,
  LanguageCode.FR_MF,
  LanguageCode.FR_MG,
  LanguageCode.FR_ML,
  LanguageCode.FR_MQ,
  LanguageCode.FR_MR,
  LanguageCode.FR_MU,
  LanguageCode.FR_NC,
  LanguageCode.FR_NE,
  LanguageCode.FR_PF,
  LanguageCode.FR_PM,
  LanguageCode.FR_RE,
  LanguageCode.FR_RW,
  LanguageCode.FR_SC,
  LanguageCode.FR_SN,
  LanguageCode.FR_SY,
  LanguageCode.FR_TD,
  LanguageCode.FR_TG,
  LanguageCode.FR_TN,
  LanguageCode.FR_VU,
  LanguageCode.FR_WF,
  LanguageCode.FR_YT,
  LanguageCode.FRR,
  LanguageCode.FRR_DE,
  LanguageCode.FUR,
  LanguageCode.FUR_IT,
  LanguageCode.FY,
  LanguageCode.FY_NL,
  LanguageCode.GA,
  LanguageCode.GA_GB,
  LanguageCode.GA_IE,
  LanguageCode.GAA,
  LanguageCode.GAA_GH,
  LanguageCode.GD,
  LanguageCode.GD_GB,
  LanguageCode.GEZ,
  LanguageCode.GEZ_ER,
  LanguageCode.GEZ_ET,
  LanguageCode.GL,
  LanguageCode.GL_ES,
  LanguageCode.GN,
  LanguageCode.GN_PY,
  LanguageCode.GSW,
  LanguageCode.GSW_CH,
  LanguageCode.GSW_FR,
  LanguageCode.GSW_LI,
  LanguageCode.GU,
  LanguageCode.GU_IN,
  LanguageCode.GUZ,
  LanguageCode.GUZ_KE,
  LanguageCode.GV,
  LanguageCode.GV_IM,
  LanguageCode.HA,
  LanguageCode.HA_ARAB,
  LanguageCode.HA_ARAB_NG,
  LanguageCode.HA_ARAB_SD,
  LanguageCode.HA_GH,
  LanguageCode.HA_NE,
  LanguageCode.HA_NG,
  LanguageCode.HAW,
  LanguageCode.HAW_US,
  LanguageCode.HE,
  LanguageCode.HE_IL,
  LanguageCode.HI,
  LanguageCode.HI_IN,
  LanguageCode.HI_LATN,
  LanguageCode.HI_LATN_IN,
  LanguageCode.HNJ,
  LanguageCode.HNJ_HMNP,
  LanguageCode.HNJ_HMNP_US,
  LanguageCode.HR,
  LanguageCode.HR_BA,
  LanguageCode.HR_HR,
  LanguageCode.HSB,
  LanguageCode.HSB_DE,
  LanguageCode.HU,
  LanguageCode.HU_HU,
  LanguageCode.HY,
  LanguageCode.HY_AM,
  LanguageCode.IA,
  LanguageCode.IA_001,
  LanguageCode.ID,
  LanguageCode.ID_ID,
  LanguageCode.IE,
  LanguageCode.IE_EE,
  LanguageCode.IG,
  LanguageCode.IG_NG,
  LanguageCode.II,
  LanguageCode.II_CN,
  LanguageCode.IO,
  LanguageCode.IO_001,
  LanguageCode.IS,
  LanguageCode.IS_IS,
  LanguageCode.IT,
  LanguageCode.IT_CH,
  LanguageCode.IT_IT,
  LanguageCode.IT_SM,
  LanguageCode.IT_VA,
  LanguageCode.IU,
  LanguageCode.IU_CA,
  LanguageCode.IU_LATN,
  LanguageCode.IU_LATN_CA,
  LanguageCode.JA,
  LanguageCode.JA_JP,
  LanguageCode.JBO,
  LanguageCode.JBO_001,
  LanguageCode.JGO,
  LanguageCode.JGO_CM,
  LanguageCode.JMC,
  LanguageCode.JMC_TZ,
  LanguageCode.JV,
  LanguageCode.JV_ID,
  LanguageCode.KA,
  LanguageCode.KA_GE,
  LanguageCode.KAA,
  LanguageCode.KAA_CYRL,
  LanguageCode.KAA_CYRL_UZ,
  LanguageCode.KAA_LATN,
  LanguageCode.KAA_LATN_UZ,
  LanguageCode.KAB,
  LanguageCode.KAB_DZ,
  LanguageCode.KAJ,
  LanguageCode.KAJ_NG,
  LanguageCode.KAM,
  LanguageCode.KAM_KE,
  LanguageCode.KCG,
  LanguageCode.KCG_NG,
  LanguageCode.KDE,
  LanguageCode.KDE_TZ,
  LanguageCode.KEA,
  LanguageCode.KEA_CV,
  LanguageCode.KEN,
  LanguageCode.KEN_CM,
  LanguageCode.KGP,
  LanguageCode.KGP_BR,
  LanguageCode.KHQ,
  LanguageCode.KHQ_ML,
  LanguageCode.KI,
  LanguageCode.KI_KE,
  LanguageCode.KK,
  LanguageCode.KK_ARAB,
  LanguageCode.KK_ARAB_CN,
  LanguageCode.KK_CYRL,
  LanguageCode.KK_CYRL_KZ,
  LanguageCode.KK_KZ,
  LanguageCode.KKJ,
  LanguageCode.KKJ_CM,
  LanguageCode.KL,
  LanguageCode.KL_GL,
  LanguageCode.KLN,
  LanguageCode.KLN_KE,
  LanguageCode.KM,
  LanguageCode.KM_KH,
  LanguageCode.KN,
  LanguageCode.KN_IN,
  LanguageCode.KO,
  LanguageCode.KO_CN,
  LanguageCode.KO_KP,
  LanguageCode.KO_KR,
  LanguageCode.KOK,
  LanguageCode.KOK_DEVA,
  LanguageCode.KOK_DEVA_IN,
  LanguageCode.KOK_LATN,
  LanguageCode.KOK_LATN_IN,
  LanguageCode.KPE,
  LanguageCode.KPE_GN,
  LanguageCode.KPE_LR,
  LanguageCode.KS,
  LanguageCode.KS_ARAB,
  LanguageCode.KS_ARAB_IN,
  LanguageCode.KS_DEVA,
  LanguageCode.KS_DEVA_IN,
  LanguageCode.KSB,
  LanguageCode.KSB_TZ,
  LanguageCode.KSF,
  LanguageCode.KSF_CM,
  LanguageCode.KSH,
  LanguageCode.KSH_DE,
  LanguageCode.KU,
  LanguageCode.KU_TR,
  LanguageCode.KW,
  LanguageCode.KW_GB,
  LanguageCode.KXV,
  LanguageCode.KXV_DEVA,
  LanguageCode.KXV_DEVA_IN,
  LanguageCode.KXV_LATN,
  LanguageCode.KXV_LATN_IN,
  LanguageCode.KXV_ORYA,
  LanguageCode.KXV_ORYA_IN,
  LanguageCode.KXV_TELU,
  LanguageCode.KXV_TELU_IN,
  LanguageCode.KY,
  LanguageCode.KY_KG,
  LanguageCode.LA,
  LanguageCode.LA_VA,
  LanguageCode.LAG,
  LanguageCode.LAG_TZ,
  LanguageCode.LB,
  LanguageCode.LB_LU,
  LanguageCode.LG,
  LanguageCode.LG_UG,
  LanguageCode.LIJ,
  LanguageCode.LIJ_IT,
  LanguageCode.LKT,
  LanguageCode.LKT_US,
  LanguageCode.LLD,
  LanguageCode.LLD_IT,
  LanguageCode.LMO,
  LanguageCode.LMO_IT,
  LanguageCode.LN,
  LanguageCode.LN_AO,
  LanguageCode.LN_CD,
  LanguageCode.LN_CF,
  LanguageCode.LN_CG,
  LanguageCode.LO,
  LanguageCode.LO_LA,
  LanguageCode.LRC,
  LanguageCode.LRC_IQ,
  LanguageCode.LRC_IR,
  LanguageCode.LT,
  LanguageCode.LT_LT,
  LanguageCode.LTG,
  LanguageCode.LTG_LV,
  LanguageCode.LU,
  LanguageCode.LU_CD,
  LanguageCode.LUO,
  LanguageCode.LUO_KE,
  LanguageCode.LUY,
  LanguageCode.LUY_KE,
  LanguageCode.LV,
  LanguageCode.LV_LV,
  LanguageCode.MAI,
  LanguageCode.MAI_IN,
  LanguageCode.MAS,
  LanguageCode.MAS_KE,
  LanguageCode.MAS_TZ,
  LanguageCode.MDF,
  LanguageCode.MDF_RU,
  LanguageCode.MER,
  LanguageCode.MER_KE,
  LanguageCode.MFE,
  LanguageCode.MFE_MU,
  LanguageCode.MG,
  LanguageCode.MG_MG,
  LanguageCode.MGH,
  LanguageCode.MGH_MZ,
  LanguageCode.MGO,
  LanguageCode.MGO_CM,
  LanguageCode.MHN,
  LanguageCode.MHN_IT,
  LanguageCode.MI,
  LanguageCode.MI_NZ,
  LanguageCode.MIC,
  LanguageCode.MIC_CA,
  LanguageCode.MK,
  LanguageCode.MK_MK,
  LanguageCode.ML,
  LanguageCode.ML_IN,
  LanguageCode.MN,
  LanguageCode.MN_MN,
  LanguageCode.MN_MONG,
  LanguageCode.MN_MONG_CN,
  LanguageCode.MN_MONG_MN,
  LanguageCode.MNI,
  LanguageCode.MNI_BENG,
  LanguageCode.MNI_BENG_IN,
  LanguageCode.MNI_MTEI,
  LanguageCode.MNI_MTEI_IN,
  LanguageCode.MOH,
  LanguageCode.MOH_CA,
  LanguageCode.MR,
  LanguageCode.MR_IN,
  LanguageCode.MS,
  LanguageCode.MS_ARAB,
  LanguageCode.MS_ARAB_BN,
  LanguageCode.MS_ARAB_MY,
  LanguageCode.MS_BN,
  LanguageCode.MS_ID,
  LanguageCode.MS_MY,
  LanguageCode.MS_SG,
  LanguageCode.MT,
  LanguageCode.MT_MT,
  LanguageCode.MUA,
  LanguageCode.MUA_CM,
  LanguageCode.MUS,
  LanguageCode.MUS_US,
  LanguageCode.MY,
  LanguageCode.MY_MM,
  LanguageCode.MYV,
  LanguageCode.MYV_RU,
  LanguageCode.MZN,
  LanguageCode.MZN_IR,
  LanguageCode.NAQ,
  LanguageCode.NAQ_NA,
  LanguageCode.NB,
  LanguageCode.NB_NO,
  LanguageCode.NB_SJ,
  LanguageCode.ND,
  LanguageCode.ND_ZW,
  LanguageCode.NDS,
  LanguageCode.NDS_DE,
  LanguageCode.NDS_NL,
  LanguageCode.NE,
  LanguageCode.NE_IN,
  LanguageCode.NE_NP,
  LanguageCode.NL,
  LanguageCode.NL_AW,
  LanguageCode.NL_BE,
  LanguageCode.NL_BQ,
  LanguageCode.NL_CW,
  LanguageCode.NL_NL,
  LanguageCode.NL_SR,
  LanguageCode.NL_SX,
  LanguageCode.NMG,
  LanguageCode.NMG_CM,
  LanguageCode.NN,
  LanguageCode.NN_NO,
  LanguageCode.NNH,
  LanguageCode.NNH_CM,
  LanguageCode.NO,
  LanguageCode.NQO,
  LanguageCode.NQO_GN,
  LanguageCode.NR,
  LanguageCode.NR_ZA,
  LanguageCode.NSO,
  LanguageCode.NSO_ZA,
  LanguageCode.NUS,
  LanguageCode.NUS_SS,
  LanguageCode.NV,
  LanguageCode.NV_US,
  LanguageCode.NY,
  LanguageCode.NY_MW,
  LanguageCode.NYN,
  LanguageCode.NYN_UG,
  LanguageCode.OC,
  LanguageCode.OC_ES,
  LanguageCode.OC_FR,
  LanguageCode.OM,
  LanguageCode.OM_ET,
  LanguageCode.OM_KE,
  LanguageCode.OR,
  LanguageCode.OR_IN,
  LanguageCode.OS,
  LanguageCode.OS_GE,
  LanguageCode.OS_RU,
  LanguageCode.OSA,
  LanguageCode.OSA_US,
  LanguageCode.PA,
  LanguageCode.PA_ARAB,
  LanguageCode.PA_ARAB_PK,
  LanguageCode.PA_GURU,
  LanguageCode.PA_GURU_IN,
  LanguageCode.PAP,
  LanguageCode.PAP_AW,
  LanguageCode.PAP_CW,
  LanguageCode.PCM,
  LanguageCode.PCM_NG,
  LanguageCode.PIS,
  LanguageCode.PIS_SB,
  LanguageCode.PL,
  LanguageCode.PL_PL,
  LanguageCode.PRG,
  LanguageCode.PRG_PL,
  LanguageCode.PS,
  LanguageCode.PS_AF,
  LanguageCode.PS_PK,
  LanguageCode.PT,
  LanguageCode.PT_AO,
  LanguageCode.PT_BR,
  LanguageCode.PT_CH,
  LanguageCode.PT_CV,
  LanguageCode.PT_GQ,
  LanguageCode.PT_GW,
  LanguageCode.PT_LU,
  LanguageCode.PT_MO,
  LanguageCode.PT_MZ,
  LanguageCode.PT_PT,
  LanguageCode.PT_ST,
  LanguageCode.PT_TL,
  LanguageCode.QU,
  LanguageCode.QU_BO,
  LanguageCode.QU_EC,
  LanguageCode.QU_PE,
  LanguageCode.QUC,
  LanguageCode.QUC_GT,
  LanguageCode.RAJ,
  LanguageCode.RAJ_IN,
  LanguageCode.RHG,
  LanguageCode.RHG_ROHG,
  LanguageCode.RHG_ROHG_BD,
  LanguageCode.RHG_ROHG_MM,
  LanguageCode.RIF,
  LanguageCode.RIF_MA,
  LanguageCode.RM,
  LanguageCode.RM_CH,
  LanguageCode.RN,
  LanguageCode.RN_BI,
  LanguageCode.RO,
  LanguageCode.RO_MD,
  LanguageCode.RO_RO,
  LanguageCode.ROF,
  LanguageCode.ROF_TZ,
  LanguageCode.ROOT,
  LanguageCode.RU,
  LanguageCode.RU_BY,
  LanguageCode.RU_KG,
  LanguageCode.RU_KZ,
  LanguageCode.RU_MD,
  LanguageCode.RU_RU,
  LanguageCode.RU_UA,
  LanguageCode.RW,
  LanguageCode.RW_RW,
  LanguageCode.RWK,
  LanguageCode.RWK_TZ,
  LanguageCode.SA,
  LanguageCode.SA_IN,
  LanguageCode.SAH,
  LanguageCode.SAH_RU,
  LanguageCode.SAQ,
  LanguageCode.SAQ_KE,
  LanguageCode.SAT,
  LanguageCode.SAT_DEVA,
  LanguageCode.SAT_DEVA_IN,
  LanguageCode.SAT_OLCK,
  LanguageCode.SAT_OLCK_IN,
  LanguageCode.SBP,
  LanguageCode.SBP_TZ,
  LanguageCode.SC,
  LanguageCode.SC_IT,
  LanguageCode.SCN,
  LanguageCode.SCN_IT,
  LanguageCode.SD,
  LanguageCode.SD_ARAB,
  LanguageCode.SD_ARAB_PK,
  LanguageCode.SD_DEVA,
  LanguageCode.SD_DEVA_IN,
  LanguageCode.SDH,
  LanguageCode.SDH_IQ,
  LanguageCode.SDH_IR,
  LanguageCode.SE,
  LanguageCode.SE_FI,
  LanguageCode.SE_NO,
  LanguageCode.SE_SE,
  LanguageCode.SEH,
  LanguageCode.SEH_MZ,
  LanguageCode.SES,
  LanguageCode.SES_ML,
  LanguageCode.SG,
  LanguageCode.SG_CF,
  LanguageCode.SHI,
  LanguageCode.SHI_LATN,
  LanguageCode.SHI_LATN_MA,
  LanguageCode.SHI_TFNG,
  LanguageCode.SHI_TFNG_MA,
  LanguageCode.SHN,
  LanguageCode.SHN_MM,
  LanguageCode.SHN_TH,
  LanguageCode.SI,
  LanguageCode.SI_LK,
  LanguageCode.SID,
  LanguageCode.SID_ET,
  LanguageCode.SK,
  LanguageCode.SK_SK,
  LanguageCode.SKR,
  LanguageCode.SKR_PK,
  LanguageCode.SL,
  LanguageCode.SL_SI,
  LanguageCode.SMA,
  LanguageCode.SMA_NO,
  LanguageCode.SMA_SE,
  LanguageCode.SMJ,
  LanguageCode.SMJ_NO,
  LanguageCode.SMJ_SE,
  LanguageCode.SMN,
  LanguageCode.SMN_FI,
  LanguageCode.SMS,
  LanguageCode.SMS_FI,
  LanguageCode.SN,
  LanguageCode.SN_ZW,
  LanguageCode.SO,
  LanguageCode.SO_DJ,
  LanguageCode.SO_ET,
  LanguageCode.SO_KE,
  LanguageCode.SO_SO,
  LanguageCode.SQ,
  LanguageCode.SQ_AL,
  LanguageCode.SQ_MK,
  LanguageCode.SQ_XK,
  LanguageCode.SR,
  LanguageCode.SR_CYRL,
  LanguageCode.SR_CYRL_BA,
  LanguageCode.SR_CYRL_ME,
  LanguageCode.SR_CYRL_RS,
  LanguageCode.SR_CYRL_XK,
  LanguageCode.SR_LATN,
  LanguageCode.SR_LATN_BA,
  LanguageCode.SR_LATN_ME,
  LanguageCode.SR_LATN_RS,
  LanguageCode.SR_LATN_XK,
  LanguageCode.SS,
  LanguageCode.SS_SZ,
  LanguageCode.SS_ZA,
  LanguageCode.SSY,
  LanguageCode.SSY_ER,
  LanguageCode.ST,
  LanguageCode.ST_LS,
  LanguageCode.ST_ZA,
  LanguageCode.SU,
  LanguageCode.SU_LATN,
  LanguageCode.SU_LATN_ID,
  LanguageCode.SV,
  LanguageCode.SV_AX,
  LanguageCode.SV_FI,
  LanguageCode.SV_SE,
  LanguageCode.SW,
  LanguageCode.SW_CD,
  LanguageCode.SW_KE,
  LanguageCode.SW_TZ,
  LanguageCode.SW_UG,
  LanguageCode.SYR,
  LanguageCode.SYR_IQ,
  LanguageCode.SYR_SY,
  LanguageCode.SZL,
  LanguageCode.SZL_PL,
  LanguageCode.TA,
  LanguageCode.TA_IN,
  LanguageCode.TA_LK,
  LanguageCode.TA_MY,
  LanguageCode.TA_SG,
  LanguageCode.TE,
  LanguageCode.TE_IN,
  LanguageCode.TEO,
  LanguageCode.TEO_KE,
  LanguageCode.TEO_UG,
  LanguageCode.TG,
  LanguageCode.TG_TJ,
  LanguageCode.TH,
  LanguageCode.TH_TH,
  LanguageCode.TI,
  LanguageCode.TI_ER,
  LanguageCode.TI_ET,
  LanguageCode.TIG,
  LanguageCode.TIG_ER,
  LanguageCode.TK,
  LanguageCode.TK_TM,
  LanguageCode.TN,
  LanguageCode.TN_BW,
  LanguageCode.TN_ZA,
  LanguageCode.TO,
  LanguageCode.TO_TO,
  LanguageCode.TOK,
  LanguageCode.TOK_001,
  LanguageCode.TPI,
  LanguageCode.TPI_PG,
  LanguageCode.TR,
  LanguageCode.TR_CY,
  LanguageCode.TR_TR,
  LanguageCode.TRV,
  LanguageCode.TRV_TW,
  LanguageCode.TRW,
  LanguageCode.TRW_PK,
  LanguageCode.TS,
  LanguageCode.TS_ZA,
  LanguageCode.TT,
  LanguageCode.TT_RU,
  LanguageCode.TWQ,
  LanguageCode.TWQ_NE,
  LanguageCode.TYV,
  LanguageCode.TYV_RU,
  LanguageCode.TZM,
  LanguageCode.TZM_MA,
  LanguageCode.UG,
  LanguageCode.UG_CN,
  LanguageCode.UK,
  LanguageCode.UK_UA,
  LanguageCode.UR,
  LanguageCode.UR_IN,
  LanguageCode.UR_PK,
  LanguageCode.UZ,
  LanguageCode.UZ_ARAB,
  LanguageCode.UZ_ARAB_AF,
  LanguageCode.UZ_CYRL,
  LanguageCode.UZ_CYRL_UZ,
  LanguageCode.UZ_LATN,
  LanguageCode.UZ_LATN_UZ,
  LanguageCode.VAI,
  LanguageCode.VAI_LATN,
  LanguageCode.VAI_LATN_LR,
  LanguageCode.VAI_VAII,
  LanguageCode.VAI_VAII_LR,
  LanguageCode.VE,
  LanguageCode.VE_ZA,
  LanguageCode.VEC,
  LanguageCode.VEC_IT,
  LanguageCode.VI,
  LanguageCode.VI_VN,
  LanguageCode.VMW,
  LanguageCode.VMW_MZ,
  LanguageCode.VO,
  LanguageCode.VO_001,
  LanguageCode.VUN,
  LanguageCode.VUN_TZ,
  LanguageCode.WA,
  LanguageCode.WA_BE,
  LanguageCode.WAE,
  LanguageCode.WAE_CH,
  LanguageCode.WAL,
  LanguageCode.WAL_ET,
  LanguageCode.WBP,
  LanguageCode.WBP_AU,
  LanguageCode.WO,
  LanguageCode.WO_SN,
  LanguageCode.XH,
  LanguageCode.XH_ZA,
  LanguageCode.XNR,
  LanguageCode.XNR_IN,
  LanguageCode.XOG,
  LanguageCode.XOG_UG,
  LanguageCode.YAV,
  LanguageCode.YAV_CM,
  LanguageCode.YI,
  LanguageCode.YI_UA,
  LanguageCode.YO,
  LanguageCode.YO_BJ,
  LanguageCode.YO_NG,
  LanguageCode.YRL,
  LanguageCode.YRL_BR,
  LanguageCode.YRL_CO,
  LanguageCode.YRL_VE,
  LanguageCode.YUE,
  LanguageCode.YUE_HANS,
  LanguageCode.YUE_HANS_CN,
  LanguageCode.YUE_HANT,
  LanguageCode.YUE_HANT_CN,
  LanguageCode.YUE_HANT_HK,
  LanguageCode.ZA,
  LanguageCode.ZA_CN,
  LanguageCode.ZGH,
  LanguageCode.ZGH_MA,
  LanguageCode.ZH,
  LanguageCode.ZH_HANS,
  LanguageCode.ZH_HANS_CN,
  LanguageCode.ZH_HANS_HK,
  LanguageCode.ZH_HANS_MO,
  LanguageCode.ZH_HANS_MY,
  LanguageCode.ZH_HANS_SG,
  LanguageCode.ZH_HANT,
  LanguageCode.ZH_HANT_HK,
  LanguageCode.ZH_HANT_MO,
  LanguageCode.ZH_HANT_MY,
  LanguageCode.ZH_HANT_TW,
  LanguageCode.ZH_LATN,
  LanguageCode.ZH_LATN_CN,
  LanguageCode.ZU,
  LanguageCode.ZU_ZA,
];
